### PR TITLE
Reverse forward/backward images for correct rendering in Arabic

### PR DESCRIPTION
**Pull request by ryancarlson**

### CODE REVIEW

**Comment by ryancarlson** [comment]
@frett or @Omicron7 can one of you take a quick look at this?

**Review by Omicron7 — APPROVED** [review]
Umm, looks good? 👍 
Any other iOS devs who could check it?

**Comment by frett** [comment]
just gave @wiseguy16 write access to the repo, so he can review PRs here if needed :)

**Review by frett — APPROVED** [review]

**Comment by ryancarlson** [comment]
This didn't work when I tested it, so closing in favor of #8 which did test correctly

**Pull request closed without merging**
