### PR TITLE
Handle 401 responses when fetching a ticket with OAuth

### PR DESCRIPTION
**Pull request by frett**

### CODE REVIEW

**Comment by frett** [comment]
my first iOS PR!!!! :)

**Comment by frett** [comment]
This should have handled your corner case access_token issue this morning

**Comment by ryancarlson** [comment]
Looks good!  The other things you need to do are:
- in `TheKeyOAuth2.Podspec` update the two version numbers there to: 0.6.4
- tag the commit where you bump the version number with: 0.6.4

I'll take it from there. 👍

**Comment by ryancarlson** [comment]
s.version and s.source both have the 0.6.3 that should be updated to 0.6.4

**Comment by frett** [comment]
updated. I haven't tested any of this code due to not really having the iOS environment set up, but in theory it should work :)

**Pull request merged**
